import Smash from './img/samashbox.avif'
import Smash2 from './img/2.avif'
import Smash3 from './img/3.avif'
import Smash4 from './img/4.avif'
import Smash5 from './img/5.avif'
import Smash6 from './img/6.avif'
import Smash7 from './img/7.avif'
import Smash8 from './img/8.avif'
import Skin1 from './img/9.avif'
import Skin2 from './img/10.avif'
import Skin3 from './img/11.avif'
import Skin4 from './img/12.avif'
import Skin5 from './img/13.avif'
import Skin6 from './img/14.avif'
import Skin7 from './img/15.avif'
import Skin8 from './img/16.avif'
import Hair1 from './img/17.avif'
import Hair2 from './img/18.avif'
import Hair3 from './img/19.avif'
import Hair4 from './img/20.avif'
import Body1 from './img/21.avif'
import Body2 from './img/22.avif'
import Body3 from './img/23.avif'
import Body4 from './img/24.avif'
import Body5 from './img/25.avif'
const Productdata = [
    {
        id: "first",
        Categories:"Makeup",
        ProductImg: Smash,
        Title: "Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 - Light Neutral (40ml)",
        Price: '₹3,510',
        Description: "This tinted moisturizer provides sheer to medium coverage while hydrating and protecting the skin with SPF 25. It's formulated with green tea and vitamins A, C, and E to help improve the appearance of fine lines and wrinkles.",
        Use :{
            Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
            Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
            "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
            "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
            "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
            "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
            "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
            "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
        },
        Ingredients:{
            Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
            Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
            Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
            Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
            Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
            Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
            Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
            Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
        },
        HowToUse: {
            HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
            HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
            HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",

        },
        Brand:"RELIANCE RETAIL LIMITED",
        Rating:5.0,
    },
    {
        id: "11",
        Categories:"Makeup",
        ProductImg: Smash3,
        Title: "Makeup Revolution IRL Filter Finish Concealer - C8.2 (6g)",
        Price: '₹611',
        Description: "This concealer provides medium to high coverage and is designed to help conceal imperfections while giving the skin a natural-looking finish. It's available in a range of shades to suit different skin tones.",
        Brand:"RELIANCE RETAIL LIMITED",
        Rating:4.0,
        Use :{
            Use1: "Makeup Revolution's IRL Filter Finish Concealer in shade C8.2 offers several versatile uses in your makeup routine:",
            Use2: "1. Concealing Imperfections: It effectively covers dark circles, blemishes, redness, and other skin imperfections, providing a smooth and even complexion.",
            "Use3": "2. Highlighting: Use it to highlight areas of your face such as the under-eye area, the bridge of the nose, the center of the forehead, and the chin to enhance your facial features.",
            "Use4": "3. Contour: Choose a shade slightly darker than your skin tone to contour and add depth to areas like the hollows of your cheeks, jawline, and sides of the nose.",
            "Use5": "4. Priming Eyelids: Apply a small amount on your eyelids as a base for eyeshadow to help the colors pop and last longer.",
            "Use6": "5. Touch-ups: Ideal for on-the-go touch-ups to maintain a fresh and flawless look throughout the day.",
           
        },
        Ingredients:{
            Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
            Ingredient2:"2. Glycerin: Humectant that helps to retain moisture.",
            Ingredient3:"3. Methyl Methacrylate Crosspolymer: Provides a blurring effect.",
            Ingredient4:"4. Cetyl PEG/PPG-10/1 Dimethicone: Emulsifying agent.",
            Ingredient5:"5. Sodium Chloride: Thickening agent.",
            Ingredient6:"6. Chlorphenesin: Preservative.",
            Ingredient7:"7. Tridecane: Solvent.",
            Ingredient8:"8. Caprylyl Glycol: Skin conditioning agent.",
        },
        HowToUse: {
            HowToUse1: "1.Prepare Your Skin Cleanse: Start with a clean face. Use your regular cleanser to remove any dirt, oil, or makeup. ",
            HowToUse2: "2. Moisturize: Apply a lightweight moisturizer to keep your skin hydrated. This helps the concealer blend smoothly.",
            HowToUse3: "3. Use a makeup sponge, brush, or your fingertips to blend the concealer into your skin. Pat the concealer gently to blend without wiping it away.",

        },
    },
    {
        id: "12",
        Categories:"Makeup",
        ProductImg: Smash2,
        Title: "Insight Cosmetics Matte Finish Full Cover Foundation - LP05 (30ml)",
        Price: '₹293',
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a matte finish. It's available in a range of shades to suit different skin tones.",
        Brand:"RELIANCE RETAIL LIMITED",
        Rating:4.2,
        Use :{
            Use1: "The Insight Cosmetics Matte Finish Full Cover Foundation - LP05 (30ml) is used for:",
            Use2: "1. Covering Imperfections: It provides full coverage to hide blemishes, scars, redness, and other skin imperfections.",
            "Use3": "2. Matte Finish: It gives your skin a matte look, reducing shine and oiliness.",
            "Use4": "3. Even Skin Tone: It helps to create an even and smooth skin tone.",
            "Use5": "4. Long-Lasting Wear: Designed to stay put throughout the day without needing frequent touch-ups..",
            "Use6": "5. Foundation Base: Acts as a base for other makeup products, ensuring they apply smoothly and last longer.",
          },
        Ingredients:{
            Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
            Ingredient2:"2. Trimethylsiloxysilicate",
            Ingredient3:"3. Butylene Glycol",
            Ingredient4:"4. Sodium Chloride",
            Ingredient5:"5. Caprylyl Glycol",
            Ingredient6:"6. Ethylhexylglycerin",
            Ingredient7:"7. PEG-10 Dimethicone.",
            Ingredient8:"9. Alumina",
        },
        HowToUse: {
            HowToUse1: "1. Prepare Your Skin Clean your face. Apply moisturizer.",
            HowToUse2: "2. Apply Foundation Put a small amount of foundation on the back of your hand.Use a brush, sponge, or your fingers to apply it to your face.Start in the center and blend outward.",
            HowToUse3: "3. Use a setting powder for a longer-lasting finish.",

        },
    },
    {
        id: "13",
        Categories:"Makeup",
        ProductImg: Smash4,
        Title: "Rom&nd Juicy Lasting Tint - 25 Bare Grape (5.5g)",
        Price: '₹890',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.8,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
            },
            Ingredients:{
                Ingredient1:"1. Ethylhexylglycerin.",
                Ingredient2:"2. 1,2-Hexanediol.",
                Ingredient3:"3. Red 27 (CI 45410).",
                Ingredient4:"4. Red 6 (CI 15850).",
                Ingredient5:"5. Yellow 5 (CI 19140).",
                Ingredient6:"6. Blue 1 (CI 42090).",
                Ingredient7:"7. Titanium Dioxide (CI 77891).",
                Ingredient8:"9. Sodium Chloride.",
            },
            HowToUse: {
                HowToUse1: "1. Make sure your lips are clean and dry.Apply a lip balm if needed to keep your lips moisturized.",
                HowToUse2: "2. Use the applicator to apply the tint directly to your lips..",
                HowToUse3: "3. Apply additional layers if you want a more intense color.",
    
            },
    },
    {
        id: "14",
        Categories:"Makeup",
        ProductImg: Smash5,
        Title: "Faces Canada Ultime Pro Makeup Fixer, Long Lasting,Hydrating Makeup Setting Spray, No alcohol-(50 ml)",
        Price: '₹331',
        Description: "This setting spray is designed to help set makeup in place for a longer-lasting finish It's formulated with hydrating ingredients to help keep the skin moisturized throughout the day.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:3.5,
            Use :{
                Use1: "Using the Faces Canada Ultime Pro Makeup Fixer is straightforward and can help your makeup last longer while keeping your skin hydrated. Here's how to use it:",
                "Use5": "1. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "2. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "3. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "4. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau.",
                Ingredient2:"2. PVP.",
                Ingredient3:"3. Disodium EDTA.",
                Ingredient4:"4. Fragrance.",
                Ingredient5:"5. Sodium Hyaluronate.",
                Ingredient6:"6. C12-15 Alkyl Benzoate.",
                Ingredient7:"7. PEG-10 Dimethicone",
                Ingredient8:"9. Aloe Barbadensis (Aloe Vera) Leaf Extract.",
            },
            HowToUse: {
                HowToUse1: "1. Apply your makeup as usual. Make sure to complete your makeup routine before using the setting spray.",
                HowToUse2: "2. Shake the bottle well to ensure the ingredients are properly mixed.",
                HowToUse3: "3. Hold the bottle about 8-10 inches away from your face. This distance ensures a fine mist covers your face evenly.",
    
            },
    },
    {
        id: "15",
        Categories:"Makeup",
        ProductImg: Smash6,
        Title: "Huda Beauty Faux Filter Luminous Matte Full Coverage Liquid Foundation - 110N Angel Food (35ml)",
        Price: '₹3,650',
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a luminous matte finish. It's available in a range of shades to suit different skin tones ",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.3,
            Use :{
                Use1: "The Insight Cosmetics Matte Finish Full Cover Foundation - LP05 (30ml) is used for:",
                Use2: "1. Covering Imperfections: It provides full coverage to hide blemishes, scars, redness, and other skin imperfections.",
                "Use3": "2. Matte Finish: It gives your skin a matte look, reducing shine and oiliness.",
                "Use4": "3. Even Skin Tone: It helps to create an even and smooth skin tone.",
                "Use5": "4. Long-Lasting Wear: Designed to stay put throughout the day without needing frequent touch-ups..",
                "Use6": "5. Foundation Base: Acts as a base for other makeup products, ensuring they apply smoothly and last longer.",
              },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Trimethylsiloxysilicate",
                Ingredient3:"3. Butylene Glycol",
                Ingredient4:"4. Sodium Chloride",
                Ingredient5:"5. Caprylyl Glycol",
                Ingredient6:"6. Ethylhexylglycerin",
                Ingredient7:"7. PEG-10 Dimethicone.",
                Ingredient8:"9. Alumina",
            },
            HowToUse: {
                HowToUse1: "1. Prepare Your Skin Clean your face. Apply moisturizer.",
                HowToUse2: "2. Apply Foundation Put a small amount of foundation on the back of your hand.Use a brush, sponge, or your fingers to apply it to your face.Start in the center and blend outward.",
                HowToUse3: "3. Use a setting powder for a longer-lasting finish.",
    
            },
    },
    {
        id: "16",
        Categories:"Makeup",
        ProductImg: Smash7,
        Title: "Maybelline New York The Colossal Liner - Black (1.2ml)",
        Price: '₹379',
        Description: "This eyeliner is designed to help create a precise, bold line. It's formulated with a waterproof formula to help keep the line in place all day.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:5.0,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
            },
            Ingredients:{
                Ingredient1:"1. Ethylhexylglycerin.",
                Ingredient2:"2. 1,2-Hexanediol.",
                Ingredient3:"3. Red 27 (CI 45410).",
                Ingredient4:"4. Red 6 (CI 15850).",
                Ingredient5:"5. Yellow 5 (CI 19140).",
                Ingredient6:"6. Blue 1 (CI 42090).",
                Ingredient7:"7. Titanium Dioxide (CI 77891).",
                Ingredient8:"9. Sodium Chloride.",
            },
            HowToUse: {
                HowToUse1: "1. Make sure your lips are clean and dry.Apply a lip balm if needed to keep your lips moisturized.",
                HowToUse2: "2. Use the applicator to apply the tint directly to your lips..",
                HowToUse3: "3. Apply additional layers if you want a more intense color.",
    
            },
    },
    {
        id: "17",
        ProductImg: Smash8,
        Categories:"Makeup",
        Title: "Maybelline New York Hypercurl Washable Mascara - Black (9.2g)",
        Price: '₹321',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.8,
            Use :{
                Use1: "The Insight Cosmetics Matte Finish Full Cover Foundation - LP05 (30ml) is used for:",
                Use2: "1. Covering Imperfections: It provides full coverage to hide blemishes, scars, redness, and other skin imperfections.",
                "Use3": "2. Matte Finish: It gives your skin a matte look, reducing shine and oiliness.",
                "Use4": "3. Even Skin Tone: It helps to create an even and smooth skin tone.",
                "Use5": "4. Long-Lasting Wear: Designed to stay put throughout the day without needing frequent touch-ups..",
                "Use6": "5. Foundation Base: Acts as a base for other makeup products, ensuring they apply smoothly and last longer.",
              },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Trimethylsiloxysilicate",
                Ingredient3:"3. Butylene Glycol",
                Ingredient4:"4. Sodium Chloride",
                Ingredient5:"5. Caprylyl Glycol",
                Ingredient6:"6. Ethylhexylglycerin",
                Ingredient7:"7. PEG-10 Dimethicone.",
                Ingredient8:"9. Alumina",
            },
            HowToUse: {
                HowToUse1: "1. Prepare Your Skin Clean your face. Apply moisturizer.",
                HowToUse2: "2. Apply Foundation Put a small amount of foundation on the back of your hand.Use a brush, sponge, or your fingers to apply it to your face.Start in the center and blend outward.",
                HowToUse3: "3. Use a setting powder for a longer-lasting finish.",
    
            },
    },
    {
        id: "18",
        ProductImg:Skin1,
        Categories:"Skin",
        Title: "Cetaphil Gentle Skin Cleanser (125ml)",
        Price: '₹375',
        Description: "This tinted moisturizer provides sheer to medium coverage while hydrating and protecting the skin with SPF 25. It's formulated with green tea and vitamins A, C, and E to help improve the appearance of fine lines and wrinkles.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.6,
            Use :{
                Use1: "Cetaphil Gentle Skin Cleanser is a versatile, mild, and non-irritating formula suitable for all skin types. Here’s how to use it:",
                Use2: "1. Twice Daily: Use the cleanser twice a day, once in the morning and once before bed, for optimal results.",
                "Use3": "2. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn.",
                "Use5": "4. Moisturize After Cleansing: Follow up with a suitable moisturizer to keep your skin hydrated and protected.",
                "Use6": "5. uitable for Sensitive Skin: This cleanser is gentle enough for sensitive skin and can be used on both the face and body.",
                },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Start by wetting your face or the area you want to cleanse with lukewarm water.",
                HowToUse2: "2. Dispense a small amount of the cleanser (about the size of a quarter) into your hand.",
                HowToUse3: "3. Dispense a small amount of the cleanser (about the size of a quarter) into your hand.",
    
            },
    },
    {
        id: "19",
        ProductImg:Skin2,
        Categories:"Skin",
        Title:"Simple Kind To Skin Refreshing Facial Wash (150ml)",
        Price: '₹399',
        Description: "This concealer provides medium to high coverage and is designed to help conceal imperfections while giving the skin a natural-looking finish. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:3.4,
            Use :{
                Use1: "The Simple Kind To Skin Refreshing Facial Wash is a gentle and effective cleanser designed to clean your skin without drying it out. Here’s a simple guide on how to use it:",
                Use2: "1. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.",
                 },
            Ingredients:{
                Ingredient1:"1. Water/Aqua.",
                Ingredient2:"2. Cyclopentasiloxane.",
                Ingredient3:"3. Butylene Glycol.",
                Ingredient4:"4. Dimethicone.",
                Ingredient5:"5. Glycerin.",
                Ingredient6:"6. C12-15 Alkyl Benzoate.",
                Ingredient7:"7. PEG-10 Dimethicone.",
                Ingredient8:"9. Sodium Chlorideg.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "20",
        ProductImg:Skin3,
        Categories:"Skin",
        Title: "Bioderma Pigmentbio Foaming Cream Brightening Exfoliating Cleanser (200ml)",
        Price: '₹879',
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a matte finish. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.2,
            Use :{
                Use1: "The Insight Cosmetics Matte Finish Full Cover Foundation - LP05 (30ml) is used for:",
                Use2: "1. Covering Imperfections: It provides full coverage to hide blemishes, scars, redness, and other skin imperfections.",
                "Use3": "2. Matte Finish: It gives your skin a matte look, reducing shine and oiliness.",
                "Use4": "3. Even Skin Tone: It helps to create an even and smooth skin tone.",
                "Use5": "4. Long-Lasting Wear: Designed to stay put throughout the day without needing frequent touch-ups..",
                "Use6": "5. Foundation Base: Acts as a base for other makeup products, ensuring they apply smoothly and last longer.",
              },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Trimethylsiloxysilicate",
                Ingredient3:"3. Butylene Glycol",
                Ingredient4:"4. Sodium Chloride",
                Ingredient5:"5. Caprylyl Glycol",
                Ingredient6:"6. Ethylhexylglycerin",
                Ingredient7:"7. PEG-10 Dimethicone.",
                Ingredient8:"9. Alumina",
            },
            HowToUse: {
                HowToUse1: "1. Prepare Your Skin Clean your face. Apply moisturizer.",
                HowToUse2: "2. Apply Foundation Put a small amount of foundation on the back of your hand.Use a brush, sponge, or your fingers to apply it to your face.Start in the center and blend outward.",
                HowToUse3: "3. Use a setting powder for a longer-lasting finish.",
    
            },
    },
    {
        id: "21",
        ProductImg:Skin4,
        Categories:"Skin",
        Title: "Plum Green Tea Pore Cleansing Face Wash - Pack Of 2 Acne Face Wash Combo",
        Price: '₹412',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                    Use :{
                        Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                        Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                        "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                        "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                        "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    },
                    Ingredients:{
                        Ingredient1:"1. Ethylhexylglycerin.",
                        Ingredient2:"2. 1,2-Hexanediol.",
                        Ingredient3:"3. Red 27 (CI 45410).",
                        Ingredient4:"4. Red 6 (CI 15850).",
                        Ingredient5:"5. Yellow 5 (CI 19140).",
                        Ingredient6:"6. Blue 1 (CI 42090).",
                        Ingredient7:"7. Titanium Dioxide (CI 77891).",
                        Ingredient8:"9. Sodium Chloride.",
                    },
                    HowToUse: {
                        HowToUse1: "1. Make sure your lips are clean and dry.Apply a lip balm if needed to keep your lips moisturized.",
                        HowToUse2: "2. Use the applicator to apply the tint directly to your lips..",
                        HowToUse3: "3. Apply additional layers if you want a more intense color.",
            
                    },
    },
    {
        id: "22",
        ProductImg:Skin5,
        Categories:"Skin",
        Title: "Plum Green Tea Gentle Revival Face Scrub - (75g)",
        Price: '₹375',
        Description: "This setting spray is designed to help set makeup in place for a longer-lasting finish It's formulated with hydrating ingredients to help keep the skin moisturized throughout the day.",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:3.4,
                    Use :{
                        Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                        Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                        "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                        "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                        "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    },
                    Ingredients:{
                        Ingredient1:"1. Ethylhexylglycerin.",
                        Ingredient2:"2. 1,2-Hexanediol.",
                        Ingredient3:"3. Red 27 (CI 45410).",
                        Ingredient4:"4. Red 6 (CI 15850).",
                        Ingredient5:"5. Yellow 5 (CI 19140).",
                        Ingredient6:"6. Blue 1 (CI 42090).",
                        Ingredient7:"7. Titanium Dioxide (CI 77891).",
                        Ingredient8:"9. Sodium Chloride.",
                    },
                    HowToUse: {
                        HowToUse1: "1. Make sure your lips are clean and dry.Apply a lip balm if needed to keep your lips moisturized.",
                        HowToUse2: "2. Use the applicator to apply the tint directly to your lips..",
                        HowToUse3: "3. Apply additional layers if you want a more intense color.",
            
                    },
    },
    {
        id: "23",
        ProductImg:Skin6,
        Categories:"Skin",
        Title: "mCaffeine Naked & Raw Tan Removal Coffee Face Scrub - (100g)",
        Price: '₹314',
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a luminous matte finish. It's available in a range of shades to suit different skin tones ",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:5.0,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "24",
        ProductImg:Skin7,
        Categories:"Skin",
        Title: "The Derma Co 1% Hyaluronic Sunscreen Aqua Gel SPF 50 Pa++ (50g)",
        Price: '₹449',
        Description: "This eyeliner is designed to help create a precise, bold line. It's formulated with a waterproof formula to help keep the line in place all day.",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.7,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "25",
        ProductImg:Skin8,
        Categories:"Skin",
        Title: "AqualogicaRadiance + Cleanse & Protect Combo",
        Price: '₹449',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "26",
        ProductImg:Hair1,
        Categories:"Hair",
        Title: "L'Oreal Professionnel Repair Shampoo 300ml, Hair Mask (250g) & Hair Serum (90ml) Combo",
        Price: "₹2,758",
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "27",
        ProductImg:Hair2,
        Categories:"Hair",
        Title: "Soulflower Rosemary Lavender Healthy Hair Oil - (225ml)",
        Price: "₹348",
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.9,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                },
                Ingredients:{
                    Ingredient1:"1. Ethylhexylglycerin.",
                    Ingredient2:"2. 1,2-Hexanediol.",
                    Ingredient3:"3. Red 27 (CI 45410).",
                    Ingredient4:"4. Red 6 (CI 15850).",
                    Ingredient5:"5. Yellow 5 (CI 19140).",
                    Ingredient6:"6. Blue 1 (CI 42090).",
                    Ingredient7:"7. Titanium Dioxide (CI 77891).",
                    Ingredient8:"9. Sodium Chloride.",
                },
                HowToUse: {
                    HowToUse1: "1. Make sure your lips are clean and dry.Apply a lip balm if needed to keep your lips moisturized.",
                    HowToUse2: "2. Use the applicator to apply the tint directly to your lips..",
                    HowToUse3: "3. Apply additional layers if you want a more intense color.",
        
                },
    },
    {
        id: "28",
        ProductImg:Hair3,
        Categories:"Hair",
        Title: "Indulekha Bringha Oil & Shampoo Combo",
        Price: "₹1,116",
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:2.2,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "29",
        ProductImg:Hair4,
        Categories:"Hair",
        Title: "Mamaearth Rosemary Hair Growth Combo (400ml)",
        Price: '₹614',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:3.3,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "30",
        ProductImg:Body1,
        Categories:"Body & Bath",
        Title: "mCaffeine Naked & Raw Coffee Body Scrub (100g)",
        Price: '₹395',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.5,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                },
                Ingredients:{
                    Ingredient1:"1. Ethylhexylglycerin.",
                    Ingredient2:"2. 1,2-Hexanediol.",
                    Ingredient3:"3. Red 27 (CI 45410).",
                    Ingredient4:"4. Red 6 (CI 15850).",
                    Ingredient5:"5. Yellow 5 (CI 19140).",
                    Ingredient6:"6. Blue 1 (CI 42090).",
                    Ingredient7:"7. Titanium Dioxide (CI 77891).",
                    Ingredient8:"9. Sodium Chloride.",
                },
                HowToUse: {
                    HowToUse1: "1. Make sure your lips are clean and dry.Apply a lip balm if needed to keep your lips moisturized.",
                    HowToUse2: "2. Use the applicator to apply the tint directly to your lips..",
                    HowToUse3: "3. Apply additional layers if you want a more intense color.",
        
                },
    },
    {
        id: "31",
        ProductImg:Body2,
        Categories:"Body & Bath",
        Title: "Dove Deep Moisture Body Wash - (800ml)",
        Price: "₹379",
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:3.3,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "32",
        ProductImg:Body3,
        Categories:"Body & Bath",
        Title: "Vaseline Intensive Care Cocoa Glow With Pure Cocoa & Shea Butter Combo",
        Price: '₹950',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:3.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "33",
        ProductImg:Body4,
        Categories:"Body & Bath",
        Title: "The English Soap Company Royal Botanic Gardens Kew Lavender & Rosemary Soap (240g)",
        Price: '₹499',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:3.5,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "34",
        ProductImg:Body5,
        Categories:"Body & Bath",
        Title: "Indulekha Ayurvedic Proprietary Medicine Soap Bar Pack (3Pcs)",
        Price: '₹322',
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.2,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
]
export default Productdata