import Smash from './img/samashbox.avif'
import Smash2 from './img/2.avif'
import Smash3 from './img/3.avif'
import Smash4 from './img/4.avif'
import Smash5 from './img/5.avif'
import Smash6 from './img/6.avif'
import Smash7 from './img/7.avif'
import Smash8 from './img/8.avif'
import Skin1 from './img/9.avif'
import Skin2 from './img/10.avif'
import Skin3 from './img/11.avif'
import Skin4 from './img/12.avif'
import Skin5 from './img/13.avif'
import Skin6 from './img/14.avif'
import Skin7 from './img/15.avif'
import Skin8 from './img/16.avif'

const Productdata = [
    {
        id: "first",
        Categories:"Makeup",
        ProductImg: Smash,
        Title: "Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 - Light Neutral (40ml)",
        Price: 35.00,
        Description: "This tinted moisturizer provides sheer to medium coverage while hydrating and protecting the skin with SPF 25. It's formulated with green tea and vitamins A, C, and E to help improve the appearance of fine lines and wrinkles.",
        Use :{
            Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
            Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
            "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
            "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
            "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
            "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
            "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
            "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
        },
        Ingredients:{
            Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
            Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
            Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
            Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
            Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
            Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
            Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
            Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
        },
        HowToUse: {
            HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
            HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
            HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",

        },
        Brand:"RELIANCE RETAIL LIMITED",
        Rating:4.5,
    },
    {
        id: "11",
        Categories:"Makeup",
        ProductImg: Smash3,
        Title: "Makeup Revolution IRL Filter Finish Concealer - C8.2 (6g)",
        Price: 32.00,
        Description: "This concealer provides medium to high coverage and is designed to help conceal imperfections while giving the skin a natural-looking finish. It's available in a range of shades to suit different skin tones.",
        Brand:"RELIANCE RETAIL LIMITED",
        Rating:4.0,
        Use :{
            Use1: "Blemishes and Acne: Effectively covers blemishes, acne scars, and other imperfections on the skin.",
            Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
            "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
            "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
            "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
            "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
            "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
            "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
        },
        Ingredients:{
            Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
            Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
            Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
            Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
            Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
            Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
            Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
            Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
        },
        HowToUse: {
            HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
            HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
            HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",

        },
    },
    {
        id: "12",
        Categories:"Makeup",
        ProductImg: Smash2,
        Title: "Insight Cosmetics Matte Finish Full Cover Foundation - LP05 (30ml)",
        Price: 40.00,
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a matte finish. It's available in a range of shades to suit different skin tones.",
        Brand:"RELIANCE RETAIL LIMITED",
        Rating:4.2,
        Use :{
            Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
            Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
            "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
            "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
            "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
            "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
            "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
            "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
        },
        Ingredients:{
            Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
            Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
            Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
            Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
            Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
            Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
            Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
            Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
        },
        HowToUse: {
            HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
            HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
            HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",

        },
    },
    {
        id: "13",
        Categories:"Makeup",
        ProductImg: Smash4,
        Title: "Rom&nd Juicy Lasting Tint - 25 Bare Grape (5.5g)",
        Price: 35.00,
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.1,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "14",
        Categories:"Makeup",
        ProductImg: Smash5,
        Title: "Faces Canada Ultime Pro Makeup Fixer, Long Lasting,Hydrating Makeup Setting Spray, No alcohol-(50 ml)",
        Price: 35.00,
        Description: "This setting spray is designed to help set makeup in place for a longer-lasting finish It's formulated with hydrating ingredients to help keep the skin moisturized throughout the day.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:3.9,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "15",
        Categories:"Makeup",
        ProductImg: Smash6,
        Title: "Huda Beauty Faux Filter Luminous Matte Full Coverage Liquid Foundation - 110N Angel Food (35ml)",
        Price: 40.00,
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a luminous matte finish. It's available in a range of shades to suit different skin tones ",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.3,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "16",
        Categories:"Makeup",
        ProductImg: Smash7,
        Title: "Maybelline New York The Colossal Liner - Black (1.2ml)",
        Price: 35.00,
        Description: "This eyeliner is designed to help create a precise, bold line. It's formulated with a waterproof formula to help keep the line in place all day.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.2,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "17",
        ProductImg: Smash8,
        Categories:"Makeup",
        Title: "Maybelline New York Hypercurl Washable Mascara - Black (9.2g)",
        Price: 35.00,
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.1,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "18",
        ProductImg:Skin1,
        Categories:"Skin",
        Title: "Cetaphil Gentle Skin Cleanser (125ml)",
        Price: 40.00,
        Description: "This tinted moisturizer provides sheer to medium coverage while hydrating and protecting the skin with SPF 25. It's formulated with green tea and vitamins A, C, and E to help improve the appearance of fine lines and wrinkles.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.4,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "19",
        ProductImg:Skin2,
        Categories:"Skin",
        Title:"Simple Kind To Skin Refreshing Facial Wash (150ml)",
        Price: 35.00,
        Description: "This concealer provides medium to high coverage and is designed to help conceal imperfections while giving the skin a natural-looking finish. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.3,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "20",
        ProductImg:Skin3,
        Categories:"Skin",
        Title: "Bioderma Pigmentbio Foaming Cream Brightening Exfoliating Cleanser (200ml)",
        Price: 40.00,
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a matte finish. It's available in a range of shades to suit different skin tones.",
            Brand:"RELIANCE RETAIL LIMITED",
            Rating:4.5,
            Use :{
                Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
            },
            Ingredients:{
                Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
            },
            HowToUse: {
                HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
    
            },
    },
    {
        id: "21",
        ProductImg:Skin4,
        Categories:"Skin",
        Title: "Plum Green Tea Pore Cleansing Face Wash - Pack Of 2 Acne Face Wash Combo",
        Price: 40.00,
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "22",
        ProductImg:Skin5,
        Categories:"Skin",
        Title: "Plum Green Tea Gentle Revival Face Scrub - (75g)",
        Price: 40.00,
        Description: "This setting spray is designed to help set makeup in place for a longer-lasting finish It's formulated with hydrating ingredients to help keep the skin moisturized throughout the day.",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "23",
        ProductImg:Skin6,
        Categories:"Skin",
        Title: "mCaffeine Naked & Raw Tan Removal Coffee Face Scrub - (100g)",
        Price: 40.00,
        Description: "This foundation provides full coverage and is designed to help conceal imperfections while giving the skin a luminous matte finish. It's available in a range of shades to suit different skin tones ",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "24",
        ProductImg:Skin7,
        Categories:"Skin",
        Title: "The Derma Co 1% Hyaluronic Sunscreen Aqua Gel SPF 50 Pa++ (50g)",
        Price: 40.00,
        Description: "This eyeliner is designed to help create a precise, bold line. It's formulated with a waterproof formula to help keep the line in place all day.",

                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
    {
        id: "25",
        ProductImg:Skin8,
        Categories:"Skin",
        Title: "AqualogicaRadiance + Cleanse & Protect Combo",
        Price: 40.00,
        Description: "This tinted lip balm provides sheer to medium coverage and is designed to help moisturize and soften the lips. It's available in a range of shades to suit different skin tones.",
                Brand:"RELIANCE RETAIL LIMITED",
                Rating:4.4,
                Use :{
                    Use1: "The Smashbox Halo Healthy Glow Tinted Moisturizer Broad Spectrum SPF 25 in Light Neutral has several uses, making it a versatile addition to your skincare and makeup routine. Here are the primary uses of this cosmetic product",
                    Use2: "1. Moisturization Hydration It hydrates the skin, providing moisture to keep your skin looking healthy and supple. This is especially beneficial for those with dry or combination skin types.",
                    "Use3": "2. Tinted Coverage Even Skin Tone It offers light to medium coverage to even out skin tone and conceal minor imperfections. The tint provides a natural, sheer finish that enhances your complexion without looking heavy. Natural Look Ideal for a no-makeup makeup look, giving you a natural, radiant glow.",
                    "Use4": "3. Sun ProtectionSPF 25 It includes broad-spectrum SPF 25, protecting your skin from harmful UVA and UVB rays. This helps prevent sunburn, premature aging, and sun damage when used as directed.Daily Sunscreen Suitable for daily use, ensuring you have basic sun protection as part of your routine.",
                    "Use5": "4. Primer and Foundation SubstitutePrimer It can act as a primer, creating a smooth base for other makeup products like foundation, blush, and powder.Foundation Substitute For those who prefer lighter coverage, it can replace traditional foundation, providing a more breathable and lightweight option.",
                    "Use6": "5. Glow EnhancerHealthy Glow Formulated to give a healthy, radiant glow to the skin, enhancing your natural luminosity.Dewy Finish It imparts a dewy finish, which is great for achieving a youthful, fresh look",
                    "Use7": "6. Skin Care BenefitsNourishing Ingredients Often contains beneficial ingredients like antioxidants, vitamins, and minerals that nourish and protect the skin.",
                    "Use8": "7. Quick and Easy ApplicationTime-Saving Combining multiple steps (moisturizer, sunscreen, foundation) into one product saves time in your daily routine.Travel-Friendly Perfect for on-the-go touch-ups or when traveling, reducing the number of products you need to carry.",
                },
                Ingredients:{
                    Ingredient1:"1. Water/Aqua/Eau: Used as a solvent for ingredients.",
                    Ingredient2:"2. Cyclopentasiloxane: A silicone that provides a silky texture and helps the product spread smoothly.",
                    Ingredient3:"3. Butylene Glycol: Acts as a humectant, drawing moisture into the skin.",
                    Ingredient4:"4. Dimethicone: A type of silicone that provides a smooth application and helps to lock in moisture.",
                    Ingredient5:"5. Glycerin: A powerful humectant that helps keep the skin hydrated.",
                    Ingredient6:"6. C12-15 Alkyl Benzoate: An emollient that provides a silky feel.",
                    Ingredient7:"7. PEG-10 Dimethicone: A silicone that helps with the product’s spreadability.",
                    Ingredient8:"9. Sodium Chloride: Used to thicken the product.",
                },
                HowToUse: {
                    HowToUse1: "1. Apply a small amount to your face and neck, blending well with your fingertips or a makeup brush.",
                    HowToUse2: "2. Use as a primer before applying foundation or other makeup products for a smooth, even base.",
                    HowToUse3: "3. Apply as a standalone product for a natural, no-m makeup look.",
        
                },
    },
]
export default Productdata